# Site settings
title: Daniele Lodola | Conseil en stratégie marketing digitale dans le Vaucluse
email: hello@danielelodola.com
description: >
  J'aide à la définition et à la mise en &oelig;uvre de stratégies marketing 
  digitales tournées vers la croissance, en France et à l'international.
baseurl: ""
url: "https://www.danielelodola.com"
facebook_username: DanieleLodolaConsulting
github_username:  danielelodola
linkedin_username: lodola
twitter_username: dlodola

# Build settings
markdown: kramdown

#paginate: 4
#paginate_path: "blog/page:num"

plugins:
  - jekyll-sitemap
#  - jekyll-paginate