# Site settings
title: Daniele Lodola | Growth Marketing &amp; Strat&eacute;gie Digitale
email: hello@danielelodola.com
description: J'aide à la définition et à la mise en &oelig;uvre de stratégies marketing digitales tournées vers la croissance, en France et à l'international.
baseurl: ""
url: "https://danielelodola.com"
facebook_username: DanieleLodolaConsulting
instagram_username: dlodola
github_username:  danielelodola
linkedin_username: lodola
twitter_username: dlodola

# Build settings
markdown: kramdown

permalink: pretty

#paginate: 4
#paginate_path: "blog/page:num"

plugins:
  - jekyll-sitemap
#  - jekyll-paginate
#  - jekyll-redirect-from

# Exclude the following folders from the build
#exclude: [doc, blog, _posts]

exclude:
  - "doc"
  - "blog"
  - "_posts"